### ISSUE TITLE
CMS: Profile Card

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/cms-college-main#33]

**Comment by lalov1** [comment]
A couple of questions: 
- Should I add the "Department" to the data def for Faculty or loop through the tags?
- Should I loop through all the titles to display them or just choose the first one? I'm only showing the first one right now
- Should I add the "Degrees" to the data def for Faculty? Maybe similar to the Title field? 

Here is what I have so far:
https://walledev.it.utsa.edu/entity/open.act?id=d1f632af81736a1b3be11e0671f220d2&type=page

**Comment by garza-utsa** [comment]
- the taxonomy for tags won't be specific to departments, I can see us utilizing that for appointment type or advisory council status, maybe.  So for the first one (departments), we should start with just a single field for "primary" department, knowing we might have to turn this into something like title down the road.

- we should loop thru all titles

- degrees should be a WYSIWYG box, I think, unless you want to implement a group with list items (kinda of like titles, repeating, with minimum 1, no (or sane) max)
- I'll be adding a planning document to the profile page issue with some more groups we should stub out in the DD

**Comment by lalov1** [comment]
I think I'm about finished:
https://walledev.it.utsa.edu/entity/open.act?id=d1f632af81736a1b3be11e0671f220d2&type=page

Two more questions? 
- Are you okay with me separating each title by comma like I'm doing in the mock-up?
- The lists for Degrees and Research Interests aren't styled like in the DLS since the class is associated with the UL (`profile-details-ul`). I tried using that style in a wrapping div, but it doesn't work since there is some flex styling associated with it. Do you want to keep them still in the a WYSIWYG or should we do each item in an incremental field like title? The easy fix would be a new style that has the following:
````
    margin-bottom: 30px;
    font-size: 20px;
    font-weight: 600;
````

Let me know your thoughts.

**Comment by garza-utsa** [comment]
- comma separated are good, that'll work
- I think we should keep this as WYSIWYG for now, so please do make the style adjustments as needed, there is a good chance these fields might vary from faculty member to member (some might use lists, other just free text)

**Comment by lalov1** [comment]
Everything is fixed, so I'm closing this out.
